# This file is used to start locally all the mon-vieux-grimoire stack.

version: "3.9"

networks:
  mon-vieux-grimoire-network:
    name: mon-vieux-grimoire-network

services:
  mon-vieux-grimoire-api:
    build:
      context: .
      dockerfile: api/Dockerfile.local
    command: ["npm", "start"]
    container_name: mon-vieux-grimoire-api
    image: mon-vieux-grimoire-api
    networks:
      - mon-vieux-grimoire-network
    ports:
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped
    volumes:
      - type: bind
        source: api/src
        target: /mon-vieux-grimoire/api/src

  mon-vieux-grimoire-client:
    build:
      context: .
      dockerfile: client/Dockerfile.local
    command: ["npm", "start"]
    container_name: mon-vieux-grimoire-client
    image: mon-vieux-grimoire-client
    networks:
      - mon-vieux-grimoire-network
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - type: bind
        source: client/src
        target: /mon-vieux-grimoire/client/src
